services:
  db:
    image: postgres:16
    container_name: template_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=db
    volumes:
      - service-template:/var/lib/postgresql/data

  server:
    container_name: template_server
    image: registry.gitlab.com/vemate/leadgen/service-template:latest
    environment:
      - DJANGO_SETTINGS_MODULE=leadgen.settings.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  service-template:
