services:
    db:
        image: postgres:16
        container_name: robot-suisses-db
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - robot-suisses-db:/var/lib/postgresql/data
    server:
        container_name: robot-suisses-server
        # image: registry.gitlab.com/vemate/leadgen/robot-suisse:latest
        build:
            context: .
            dockerfile: server/Dockerfile-dev
        environment:
            - DJANGO_SETTINGS_MODULE:robot-suisses.settings.dev
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
volumes:
    robot-suisses-db:
